### ISSUE TITLE
Prose elements are non-responsive

### ISSUE THREAD

**Issue by sannek** [lustre-labs/ui#11]
`prose` elements get cut-off on smaller screens because they're always 60 characters wide.

```css
.lustre-ui-prose,
use-lustre-ui .prose {
  --width: 60ch;
  width: var(--width);
}
```
